workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'

variables:
    IMAGE_NAME: crisphung/itss-fe
    IMAGE_TAG: v1

stages:
    - build
    - docker
default:
    tags:
        - docker

cache:
    - key: cache
      paths:
        - /node_modules

build job:
    stage: build

    image: node:18-alpine

    script:
        - npm install --force
        - npm run build
    
    artifacts:
        paths:
            - /build
        expire_in: 1 week

docker job:
    stage: docker

    image: docker:20.10.22

    services:
        - docker:20.10.22-dind
    
    variables:
        DOCKER_TLS_CERTDIR: ""
    
    script:
        - docker login -u $DOCKER_USER -p $DOCKER_PWD
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG


